"""
Django settings for ops project.

Generated by 'django-admin startproject' using Django 1.11.16.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&0tif7khdl6-^j2k6fdwv_r%wuh%d-jqe()60#@k^bb+1_5#4q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'dashboard.apps.DashboardConfig',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ops.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'ops',
		'USER': 'root',
		'PASSWORD': 'Ryan!@99',
		'HOST': '101.132.45.51',
		'PORT': 3306,
		'OPTIONS':{
			'init_command':'SET default_storage_engine=INNODB;',
		}
	}
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # 是否禁用一些存在的配置
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
	    'default':{
		    'format':'%(asctime)s  %(name)s  %(levelname)s  [%(lineno)s]   %(message)s',
		    'datefmt':'%Y-%m-%d %H:%M:%S'
	    }
    },

    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'default'
        },
	    'file': {
		    'level': 'DEBUG',
		    'class': 'logging.handlers.TimedRotatingFileHandler',
		    'filename': './logs/debug.log',
		    'when':"D",
		    'interval':1,
		    'formatter':'default'
	    },
	    'request':{
		    'level':'DEBUG',
		    'class':'logging.FileHandler',
		    'filename':'./logs/request.log',
		    'formatter':'default',
	    },
	    'server':{
		    'level':'DEBUG',
		    'class':'logging.FileHandler',
		    'filename':'./logs/server.log',
		    'formatter':'default',
	    },
	    'root':{
		    'level': 'DEBUG',
		    'class': 'logging.FileHandler',
		    'filename': './logs/root.log',
		    'formatter': 'default',
	    },
	    'db_backends':{
	        'level': 'DEBUG',
		    'class': 'logging.FileHandler',
		    'filename': './logs/db_backends.log',
		    'formatter': 'default',
	    }

    },
    'loggers': {
	    'reboot':{

		    'level':'DEBUG',
		    'handlers':['console','file'],
		    'propagate':True,
	    },
	    'django':{
		    'level': 'DEBUG',
		    'handlers': ['console', 'file'],
			'propagate':True,
	    },

	    'django.request':{
		    'level': 'DEBUG',
		    'handlers': ["request"],
			'propagate':True,
	    },
	    'django.server':{
		    'level': 'DEBUG',
		    'handlers': ["server"],
			'propagate':True,
	    },
	    'django.db.backends':{
		    'level': 'DEBUG',
		    'handlers': ["db_backends"],
			'propagate':False,
	    }


    },
	'root':{
	    'level': 'DEBUG',
	    'handlers': ["root"],

	}
}






