# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-05 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机房名称')),
                ('address', models.CharField(max_length=256, verbose_name='机房地址')),
                ('phone', models.CharField(max_length=15, verbose_name='机房联系电话')),
                ('email', models.EmailField(max_length=254)),
                ('letter', models.CharField(max_length=5, verbose_name='idc 字母简称')),
            ],
        ),
    ]
